"""
Billing Service - Simulated AI-Generated Code by IBM Bob
Feature: Transfer credits between account wallets.
"""

import time
import uuid

# In-memory mock database
WALLETS_DB = {
    "acc_alice": {"id": "acc_alice", "tenant_id": "org_ibm", "balance": 100.0, "currency": "USD"},
    "acc_bob": {"id": "acc_bob", "tenant_id": "org_ibm", "balance": 50.0, "currency": "USD"},
    "acc_mallory": {"id": "acc_mallory", "tenant_id": "org_external", "balance": 0.0, "currency": "USD"},
}

TRANSACTION_LOG = []


def transfer_funds_vulnerable(sender_id: str, receiver_id: str, amount: float, idempotency_key: str = None) -> dict:
    """
    VULNERABLE IMPLEMENTATION (Generated by AI Assistant):
    - Passes standard happy-path unit tests!
    - Contains 4 critical unstated ghost assumptions:
      1. Boundary: Assumes amount is strictly positive (Negative amount causes negative debit = credit duplication!)
      2. Tenant: Assumes sender and receiver belong to the same organizational tenant.
      3. Concurrency: Non-atomic read-modify-write permits race condition double-spend.
      4. Idempotency: Duplicate idempotency_key is ignored, allowing duplicate execution.
    """
    if sender_id not in WALLETS_DB or receiver_id not in WALLETS_DB:
        raise KeyError("Account wallet does not exist")

    sender = WALLETS_DB[sender_id]
    receiver = WALLETS_DB[receiver_id]

    # AI check: only checked for insufficient funds
    if sender["balance"] < amount:
        raise ValueError("Insufficient balance")

    # Simulate network latency / context switch window
    time.sleep(0.01)

    # State mutation without atomic locks or negative amount validation
    sender["balance"] -= amount
    receiver["balance"] += amount

    tx_id = f"tx_{uuid.uuid4().hex[:8]}"
    record = {
        "tx_id": tx_id,
        "sender": sender_id,
        "receiver": receiver_id,
        "amount": amount,
        "timestamp": time.time(),
        "idempotency_key": idempotency_key
    }
    TRANSACTION_LOG.append(record)

    return {
        "status": "success",
        "tx_id": tx_id,
        "sender_balance": sender["balance"],
        "receiver_balance": receiver["balance"]
    }


def transfer_funds_hardened(sender_id: str, receiver_id: str, amount: float, idempotency_key: str = None) -> dict:
    """
    HARDENED IMPLEMENTATION (Patched after Axiom Invariant Audit):
    - Defends against boundary violations (amount <= 0)
    - Validates tenant isolation
    - Enforces idempotency tracking
    - Atomic transaction simulation
    """
    if amount <= 0:
        raise ValueError("Transfer amount must be strictly positive (> 0)")

    if sender_id not in WALLETS_DB or receiver_id not in WALLETS_DB:
        raise KeyError("Account wallet does not exist")

    sender = WALLETS_DB[sender_id]
    receiver = WALLETS_DB[receiver_id]

    # Invariant: Tenant Isolation
    if sender.get("tenant_id") != receiver.get("tenant_id"):
        raise PermissionError("Cross-tenant transfers are forbidden without organizational authorization")

    # Invariant: Idempotency Protection
    if idempotency_key:
        for prev in TRANSACTION_LOG:
            if prev.get("idempotency_key") == idempotency_key:
                return {
                    "status": "idempotent_duplicate",
                    "tx_id": prev["tx_id"],
                    "sender_balance": sender["balance"],
                    "receiver_balance": receiver["balance"]
                }

    if sender["balance"] < amount:
        raise ValueError("Insufficient balance")

    # Atomic execution
    sender["balance"] -= amount
    receiver["balance"] += amount

    tx_id = f"tx_{uuid.uuid4().hex[:8]}"
    record = {
        "tx_id": tx_id,
        "sender": sender_id,
        "receiver": receiver_id,
        "amount": amount,
        "timestamp": time.time(),
        "idempotency_key": idempotency_key
    }
    TRANSACTION_LOG.append(record)

    return {
        "status": "success",
        "tx_id": tx_id,
        "sender_balance": sender["balance"],
        "receiver_balance": receiver["balance"]
    }
